---
title: "Version control"
author: "Andrew Irwin"
date: "2024-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usethis)
library(gitcreds)
```

A demonstration of using version control software with Rstudio.

* Test git is working by typing `git` in the Terminal window. (Do you get a short 1-2 line error message or more than 30 lines of usage information?)
* Introduce yourself to git if you haven't done this before by typing these lines in the `Terminal` window
    -   `git config --global user.email "you@example.com"`
    -   `git config --global user.name "Your Name"`
* You need to get Rstudio and GitHub to communicate with each other. You need to create a GitHub personal access token (PAT) and tell R about it.
    - Make sure the packages `usethis` and `gitcreds` are installed. Type `library(usethis)` and `library(gitcreds)` to check. If you get an error install them using `install.packages("usethis")` and `install.packages("gitcreds")`
    - In the R console, type `usethis::create_github_token()`. This will open up a web browser. You will be asked to login and perhaps use two factor authentication. Enter a note to describe the token and pick an expiry date (I suggest a date shortly after the end of this course.) Make sure you have at least the following boxes checked: repo, user, workflow. Click the green generate token button at the bottom of the screen.
    - Copy the random numbers and letters that make up your token by clicking the two overlapping blue boxes (or highlight and select copy from the menu).
    - In the R console, type `gitcreds::gitcreds_set()`, enter, and then enter the PAT by pasting it into the console.
* Go to github web page: [github.com](https://github.com/)
* Find your assignment repository
* Create a new project on your computer using Rstudio and this repository
* Edit a file
* Stage and commit the changes
* Push the changes to github
* See that the changes have appeared on the github website
