---
title: "Create repositories for Assignments"
author: "AJ Irwin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse, quietly = TRUE)
library(ghclass)
```

## Read project team list


```{r}
team_list <- read_csv("~/Dropbox/Teaching/STAT 2430 Data Viz/2026W/Student-assignments/teams-v1.csv")
team_list |> filter(is.na(group))
```


## Get list of current repositories

```{r}
github_whoami()
org_name = "Dalhousie-AndrewIrwin-Teaching"
# org_exists(org_name)  # just checking!
org_sitrep(org_name)
# repos <- org_repos(org_name) # all of them
repos <- org_repos(org_name, filter = "data-viz-project-.*") # student assignment repositories
```

## Create repositories

Make list of repos to create.

```{r}
team_list <- team_list |> mutate(full_project_repo = paste0(org_name, "/", "data-viz-project-", sprintf("%02d", group))) |>
  mutate(project_repo = paste0("data-viz-project-",  sprintf("%02d", group))) |>
  filter(!(full_project_repo %in% repos)) |>
  filter(!is.na(github))
```

Create a repo

```{r}
create_repo <- function(team_number) {
  team_name = paste0("Team-", sprintf("%02d", team_number))
  users <- team_list |> filter(team_number == group) %>% pull(github)
  org_create_assignment(org = org_name,
                        repo = paste0("data-viz-project-", sprintf("%02d", team_number)),
                        user = users,
                        team = team_name,
                        source_repo = paste0(org_name, "/data-viz-project"),
                        private = TRUE)
}
tl <- unique(team_list$group) # |> setdiff(1)
for (i in tl) create_repo(i)
```

Somethign didn't work right. Teams exist/were created but were not added to the project repos.

Try again to add teams to repos.
Then try to add members to teams.

```{r}
repos <- org_repos(org_name, filter = "data-viz-project-.*") # student assignment repositories

for (i in 1:length(repos)) {
  repo <- repos[i]
  team <- paste0("Team-", substring(repo, nchar(repo)-1))

  repo_team_permission(  repo       = repo,
                       team       = team,
                       permission = "maintain", # or "admin", "triage", :maintain
                       team_type  = "name")
}

```

Add users to teams

```{r}
# read list again if necessary
team_list <- read_csv("~/Dropbox/Teaching/STAT 2430 Data Viz/2026W/Student-assignments/teams-v1.csv")
team_list |> filter(is.na(group))
team_list <- team_list |> mutate(full_project_repo = paste0(org_name, "/", "data-viz-project-", sprintf("%02d", group))) |>
  mutate(project_repo = paste0("data-viz-project-",  sprintf("%02d", group))) |>
  # filter(!(full_project_repo %in% repos)) |>
  filter(!is.na(github))


team_list

for (i in 1:nrow(team_list)) {
  team_name = paste0("Team-", sprintf("%02d", team_list$group[i]))
  user = team_list$github[i]
  # Invite the user to the team. 
  team_invite(
    org       = org_name,
    user      = user,
    team      = team_name,
    team_type = "name"  # use "slug" if you pass the team's slug
  )
}
```
