---
title: "Create repositories for Assignments"
author: "AJ Irwin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse, quietly = TRUE)
library(ghclass)
```

## Make a class list

Start by collecting GitHub names for each student using a Google form or other tool. Write these into a file with headings (name, email, github). Put these in the parent directory for this folder (or in another convenient place not in the repository).

```{r}
name_id_location <- "~/Dropbox/Teaching/STAT 2430 Data Viz/2026W/Student-assignments/GitHub User Name (Responses).xlsx"
# github <- read_csv(name_id_location)
github <- readxl::read_excel(name_id_location) |> janitor::clean_names()
github <- github |> 
  rename(github_account = create_a_git_hub_account_from_the_git_hub_web_page_click_on_the_user_menu_in_the_upper_right_select_your_profile_paste_the_web_address_url_in_the_blank_below) |>
  add_row(timestamp = now(),
          your_name = "Andrew Irwin",
          your_dalhousie_email_address = "stat2430-student@mmab.ca",
          your_student_number_starting_with_b0 = "B00123456",
          github_account = "https://github.com/stat2430-student") |>
  mutate(Github = basename(github_account)) 
write_csv(github, "~/Dropbox/Teaching/STAT 2430 Data Viz/2026W/Student-assignments/GitHub-User-Name.csv")
```


## Get list of current repositories

```{r}
github_whoami()
org_name = "Dalhousie-AndrewIrwin-Teaching"
# org_exists(org_name)  # just checking!
org_sitrep(org_name)
# repos <- org_repos(org_name) # all of them
repos <- org_repos(org_name, filter = "data-viz-assignments-.*") # student assignment repositories
```

## Create repositories

Make list of repos to create.

```{r}
github2 <- github |> mutate(full_assignment_repo = paste0(org_name, "/", "data-viz-assignments-", Github)) |>
  mutate(assignment_repo = paste0("data-viz-assignments-", Github)) |>
  select(-timestamp) |>
  filter(!(full_assignment_repo %in% repos)) |>
  distinct()
```

Create a repo

```{r}
create_repo <- function(i) {
  org_create_assignment(org = org_name,
                        repo = github2$assignment_repo[i],
                        user = github2$Github[i],
                        source_repo = paste0(org_name, "/data-viz-assignments"),
                        private = TRUE)
}
for (i in 1:nrow(github2)) create_repo(i)
```


