project:
  type: website
  render: 
    - "*.qmd"
    - "!06-demo-assignment-github.qmd"

website:
  title: "data-viz"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: 001-syllabus.qmd
        text: Syllabus
      - href: 002-detailed-outline.qmd
        text: Schedule
      - href: 004-evaluation.qmd
        text: Evaluation
       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



