---
title: "Data Visualization"
subtitle: "STAT 2430 at Dalhousie University, Fall 2022"
author: "Andrew Irwin"
date: "`r Sys.Date()`"
format: 
  html:
    code-line-numbers: true
editor: source
---

Welcome to Data Visualization (STAT 2430) at Dalhousie University for Fall 2022. From this page you can access all the required elements of the course including

* the [syllabus](001-syllabus.qmd) for the whole course,
* the course [textbook](https://andrewirwin.github.io/data-viz-notes/),
* the [detailed outline](002-detailed-outline.qmd) with a plan for each class (subject to change!) and a link to slides and other materials presented in class, and
* detailed information about all work to be [evaluated](004-evaluation.qmd).

A few items are located on [Brightspace course page](https://dal.brightspace.com/d2l/home/232100)

* a link to participate online through Collaborate, in case you can't come to a class,
* recordings from class,
* course work to be submitted during the first two weeks of term,
* term project information: team membership, presentation schedule, and peer-evaluation schedule,
* your grades in the course.

If you have questions about the course, please ask in class, or contact me by [email](mailto:a.irwin@dal.ca).

