---
title: "Version control"
author: "Andrew Irwin, a.irwin@dal.ca"
date: "2022-09-15"
format:
  revealjs:
    slide-number: true
    theme:  default
    chalkboard: true
    auto-animate: true
    scrollable: true
    code-block-border-left: true
    code-copy: false
    code-link: true
    history: false
---

## What is version control software for?

* Managing changes to files

* Tracking versions between major revisions 

* Sharing data, code, and results with team members

* Sharing data, code, and results with the world 


## Why is version control software important for visualizations?

* Manage changes to data

* Facilitate collaboration

* Organize revision to methods

* Manage your archive of past methods and results

* Distribute data, methods and results


## Core git concepts

* Working directory

* Repository

* Stage (add) files

* Commit to repository

* Commit messages


## What is github?

* Internet service to manage repository in remote location ("remotes")

* Collaboration tool

* Many other services (error checking, websites, teams, feedback)

* _Need a free account_. Sign up at github.com


## How to use git and github with Rstudio?

* Create a project with a git repository

* Use the "git" pane to stage, commit, and push to remote (github)


## Demonstrations

* See step-by-step instructions in lesson 6


## Suggested reading

* Course notes: Version control

* [Intro to Data Science](https://www.introds.org/) course slides on [version control](https://ids-s1-20.github.io/slides/week-01/w1-d06-toolkit-git/w1-d06-toolkit-git.html#1)

* [Data science in a box](https://datasciencebox.org/) chapter on [version control](https://datasciencebox.org/version-control.html)

* Bryan and others. [Happy git with R](https://happygitwithr.com/)


# Task

* Practice this skill in Assignment 1

* Live demo in class (I'll write the time that the demo starts in the recording once class is over.)

